# Generated by Django 3.1.4 on 2021-04-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('corriente', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Obras',
        ),
        migrations.DeleteModel(
            name='Personaje',
        ),
    ]
