# Generated by Django 3.1.4 on 2021-05-11 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0003_auto_20210511_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='apellido_materno',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='apellido_paterno',
            new_name='nacionalidad',
        ),
        migrations.AddField(
            model_name='obra',
            name='nombre',
            field=models.CharField(default='Obra', max_length=255),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subastas.usuario'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subastas.artista'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subastas.usuario'),
        ),
    ]
