# Generated by Django 3.1.4 on 2021-05-12 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0004_auto_20210511_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compradores', to='subastas.usuario'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personaje', to='subastas.artista'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='duenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='subastas.vendedor'),
        ),
        migrations.AlterField(
            model_name='puja',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pujador', to='subastas.comprador'),
        ),
        migrations.AlterField(
            model_name='puja',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieza', to='subastas.obra'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='articulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objeto', to='subastas.obra'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='subastas.usuario'),
        ),
    ]
