# Generated by Django 3.2.3 on 2021-06-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0005_auto_20210512_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puja',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujador', to='subastas.comprador'),
        ),
    ]
