# Generated by Django 3.2.3 on 2021-06-08 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subastas', '0006_alter_puja_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compradores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to=settings.AUTH_USER_MODEL),
        ),
    ]
