# Generated by Django 3.2.3 on 2021-06-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0007_auto_20210608_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compradores', to='subastas.usuario'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='subastas.usuario'),
        ),
    ]
