# Generated by Django 3.2.3 on 2021-06-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0008_auto_20210608_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprador',
            old_name='usuario_id',
            new_name='usuario_comprador',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='usuario_id',
            new_name='usuario_vendedor',
        ),
    ]
