# Generated by Django 3.2.3 on 2021-06-13 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0010_auto_20210608_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='fecha',
        ),
        migrations.AddField(
            model_name='sala',
            name='fecha_cierre',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='hora_cierre',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
